CREATE TABLE cards(
id DOUBLE NOT NULL,
game_id DOUBLE NOT NULL,
rarity VARCHAR(200) NOT NULL,
attribute VARCHAR(200) NOT NULL,
japanese_attribute VARCHAR(200) NOT NULL,
is_promo VARCHAR(200) NOT NULL,
promo_item VARCHAR(200) NOT NULL,
release_date VARCHAR(200) NOT NULL,
japan_only VARCHAR(200) NOT NULL,
is_special VARCHAR(200) NOT NULL,
hp DOUBLE NOT NULL,
minimum_statistics_smile DOUBLE NOT NULL,
minimum_statistics_pure DOUBLE NOT NULL,
minimum_statistics_cool DOUBLE NOT NULL,
non_idolized_maximum_statistics_smile DOUBLE NOT NULL,
non_idolized_maximum_statistics_pure DOUBLE NOT NULL,
non_idolized_maximum_statistics_cool DOUBLE NOT NULL,
idolized_maximum_statistics_smile DOUBLE NOT NULL,
idolized_maximum_statistics_pure DOUBLE NOT NULL,
idolized_maximum_statistics_cool DOUBLE NOT NULL,
skill VARCHAR(200) NOT NULL,
japanese_skill VARCHAR(200) NOT NULL,
skill_details VARCHAR(400) NOT NULL,
center_skill VARCHAR(200) NOT NULL,
center_skill_details VARCHAR(200) NOT NULL,
japanese_center_skill VARCHAR(200) NOT NULL,
japanese_center_skill_details VARCHAR(200) NOT NULL,
card_image VARCHAR(200) NOT NULL,
card_idolized_image VARCHAR(200) NOT NULL,
english_card_image VARCHAR(200) NOT NULL,
english_card_idolized_image VARCHAR(200) NOT NULL,
round_card_image VARCHAR(200) NOT NULL,
round_card_idolized_image VARCHAR(200) NOT NULL,
english_round_card_image VARCHAR(200) NOT NULL,
english_round_card_idolized_image VARCHAR(200) NOT NULL,
video_story VARCHAR(200) NOT NULL,
website_url VARCHAR(400) NOT NULL,
non_idolized_max_level DOUBLE NOT NULL,
idolized_max_level DOUBLE NOT NULL,
transparent_image VARCHAR(400) NOT NULL,
transparent_idolized_image VARCHAR(400) NOT NULL,
total_owners DOUBLE NOT NULL,
total_wishlist DOUBLE NOT NULL,
ranking_attribute DOUBLE NOT NULL,
ranking_rarity DOUBLE NOT NULL,
PRIMARY KEY (id));

CREATE TABLE skill_up_cards(
id DOUBLE NOT NULL,
card_id DOUBLE NOT NULL,
round_card_image VARCHAR(200) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (card_id) REFERENCES cards(id)
);

CREATE TABLE idol(
id DOUBLE NOT NULL,
note VARCHAR(400) NOT NULL,
school VARCHAR(200) NOT NULL,
name VARCHAR(200) NOT NULL,
year VARCHAR(200) NOT NULL,
chibi VARCHAR(200) NOT NULL,
main_unit VARCHAR(200) NOT NULL,
japanese_name VARCHAR(200) NOT NULL,
chibi_small VARCHAR(400) NOT NULL,
sub_unit VARCHAR(200) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (id) REFERENCES cards(id)
);

